-- Supabase table schema for excuses.me
-- Run this in Supabase SQL editor or via psql

create table if not exists excuses (
  id         bigint generated by default as identity primary key,
  text       text not null,
  region     text not null,
  tone       text not null,
  length     text not null,
  likes      integer not null default 0,
  status     text not null default 'approved',
  user_id    uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists excuses_created_at_idx on excuses (created_at desc);
create index if not exists excuses_likes_idx      on excuses (likes desc);
create index if not exists excuses_status_idx     on excuses (status);

-- Atomic like increment — prevents race conditions
create or replace function increment_likes(excuse_id bigint)
returns integer
language sql
volatile
security definer
as $$
  update excuses
  set likes = likes + 1
  where id = excuse_id
  returning likes;
$$;

-- Migration: add new columns to existing tables
-- Run these if the table already exists:
--
-- alter table excuses add column if not exists status  text not null default 'approved';
-- alter table excuses add column if not exists user_id uuid references auth.users(id) on delete set null;
